
# This is a basic workflow to help you get started with Actions
name: IaC Deployment
env:
  RESOURCE_GROUP: 'aksrunners-rg'
  CLUSTER_NAME: 'aksrunners-aks'
  ADMIN_USERNAME: 'aksadmin'
  REGION: 'East US'
  REGISTRY: ghcr.io
  IMAGE_NAME: "${{ github.repository }}"
# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches: 
      - main
    paths: 
      - 'infra/**' 
      - 'runner/**'
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code 
      uses: actions/checkout@v3
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
          client-id: "fcbaa45a-b07d-4675-bb03-4ed105f0b94e"
          tenant-id: "4e31fdef-8b04-47cb-a9f6-8c0b2ad482e1"
          subscription-id: "d105f22e-7313-4267-b3b2-572544fc707a"
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: "d105f22e-7313-4267-b3b2-572544fc707a"
        scope: subscription
        region: ${{ env.REGION }}
        template: ./infra/main.bicep
        parameters: resourcegroup="${{ env.RESOURCE_GROUP }}" aksclustername="${{ env.CLUSTER_NAME }}" adminusername="${{ env.ADMIN_USERNAME }}" sshpublickey="${{ secrets.SSH_PUBLIC_KEY }}"
        failOnStdErr: false
    - name: Set AKS context
      id: set-context
      uses: azure/aks-set-context@v3
      with:
        resource-group: '${{ env.RESOURCE_GROUP }}' 
        cluster-name: '${{ env.CLUSTER_NAME }}'
    - name: Install Runner
      run: |
          kubectl apply -f ./runner/cert-manager.yaml 
          kubectl create -f ./runner/actions-runner-controller.yaml 
          kubectl create secret generic controller-manager  -n actions-runner-system --from-literal=github_token=${{ secrets.RUNNER_TOKEN }}
          sleep 90
          kubectl apply -f ./runner/runnerdeployment.yaml 
          kubectl apply -f ./runner/hra-scaler.yaml
